// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKdbInstallation():Promise<string>;

export function ForceStartKdb():Promise<void>;

export function GetKdbPort():Promise<number>;

export function GetKdbStatus():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ResetKdbServer():Promise<string>;

export function RestartKdb():Promise<void>;

export function StartKdb():Promise<void>;

export function StopKdb():Promise<void>;

export function TestKdbConnection():Promise<string>;
