// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKdbInstallation() {
  return window['go']['main']['App']['CheckKdbInstallation']();
}

export function ForceStartKdb() {
  return window['go']['main']['App']['ForceStartKdb']();
}

export function GetKdbPort() {
  return window['go']['main']['App']['GetKdbPort']();
}

export function GetKdbStatus() {
  return window['go']['main']['App']['GetKdbStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetKdbServer() {
  return window['go']['main']['App']['ResetKdbServer']();
}

export function RestartKdb() {
  return window['go']['main']['App']['RestartKdb']();
}

export function StartKdb() {
  return window['go']['main']['App']['StartKdb']();
}

export function StopKdb() {
  return window['go']['main']['App']['StopKdb']();
}

export function TestKdbConnection() {
  return window['go']['main']['App']['TestKdbConnection']();
}
